# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    versions: '3.1.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/UnitTests.Desorganizze.csproj'
    feedsToUse: 'select'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'build'
#    projects: '**/*.sln'
#    arguments: '--configuration $(buildConfiguration)'
#  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/UnitTests.Desorganizze.csproj'
    arguments: -c $(buildConfiguration) -v n
  displayName: 'Running Unit Tests'
