version: "3.9"
services:
  desorganizze_web:
    build: .
    ports:
      - "5000:5000"
  desorganizze_seq:
    environment: 
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    image: datalust/seq